pipelines:
  - name: email_notifications
    steps:
      - name: email_onStart
        type: bash
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
            - send_notification trriplejay_smtp --recipients "john@shippable.com" "stockbauer@gmail.com"
          onExecute:
            - echo "executing"
      - name: email_onExecute
        type: bash
        requires:
          integrations:
            - trriplejay_smtp
        triggeredBy:
          steps:
            - email_onStart
        execution:
          onExecute:
            - echo "hello world"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"

      - name: email_onFailure
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - |
              echo "trying something"
              echo "mulitple commands"
              ls $STEP_TEMP_DIR
              cat badfile
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
            - send_notification trriplejay_smtp --show-failing-commands --recipients "john@shippable.com"
          onComplete:
            - echo "complete"

      - name: email_onComplete_success
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onComplete_failure
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - cat badfile
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onComplete_badOnSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful?"
            - cat badfile
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_attachments
        type: bash
        triggeredBy:
          steps:
            - email_onStart
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onExecute:
            - send_notification trriplejay_smtp --attach-logs --recipients "john@shippable.com" "stockbauer@gmail.com"
            - send_notification trriplejay_smtp --recipients "john@shippable.com" "stockbauer@gmail.com" --attach-logs

      - name: email_quick
        type: bash
        triggeredBy:
          steps:
            - email_onStart
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onExecute:
            - printenv
