pipelines:
  - name: email_notifications
    steps:
      - name: email_onStart
        type: bash
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
            - send_notification trriplejay_smtp --recipients "john@shippable.com" "stockabuer@gmail.com"
          onExecute:
            - echo "executing"
      - name: email_onExecute
        type: bash
        requires:
          integrations:
            - trriplejay_smtp
        triggeredBy:
          steps:
            - email_onStart
        execution:
          onExecute:
            - echo "hello world"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"

      - name: email_onFailure
        type: bash
        triggeredBy:
          steps:
            - email_onExecute
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - cat badfile
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"
          onComplete:
            - echo "complete"

      - name: email_onComplete_success
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onComplete_failure
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
            - cat badfile
          onSuccess:
            - echo "successful"
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"

      - name: email_onComplete_badOnSuccess
        type: bash
        triggeredBy:
          steps:
            - email_onSuccess
        requires:
          integrations:
            - trriplejay_smtp
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "executing"
          onSuccess:
            - echo "successful?"
            - cat badfile
          onFailure:
            - echo "failure"
          onComplete:
            - echo "complete"
            - send_notification trriplejay_smtp --recipients "john@shippable.com"
