pipelines:
  - name: jira_notifications
    steps:
      - name: jira_on_failure
        type: Bash
        configuration:
          integrations:
            - name: johns_jira
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "ls -latr" > runTests.sh
            - bash runTests.sh > output.log
            - cd baddirectory
          onFailure:
            - send_notification johns_jira --project-id "FROG" --description "this is a v2 api call" --type Bug --attach-file "output.log" --summary "using v2"
