pipelines:
  - name: jira_notifications
    steps:
      - name: jira_on_failure
        type: Bash
        configuration:
          integrations:
            - name: johns_jira
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - bash runTests.sh > output.log # execute the "tests" and write the output to a file
            - cd baddirectory   # force a failure for the sake of the example
          onFailure:
            - send_notification johns_jira --project-id "FROG" --description "Failure occured in $pipeline_name - $step_name" --type Bug --attach-file "output.log" --summary "$step_name has failed"
