resources:
  - name: start_all
    type: PropertyBag
    configuration:
      hello: world

pipelines:
  - name: pagerduty_notifications
    configuration:
      environmentVariables:
        myRoutingKey: 8c22b13ccaa04da79a9952761248c337
    steps:
      - name: ps_pagerduty_success
        type: PowerShell
        configuration:
          nodePool: static-win
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty -routingkey $myRoutingKey -text "hello world"

      - name: bash_pagerduty_success
        type: Bash
        configuration:
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty

