resources:
  - name: start_all
    type: PropertyBag
    configuration:
      hello: world

pipelines:
  - name: pagerduty_notifications
    steps:
      - name: pagerduty_success_ps
        type: PowerShell
        configuration:
          nodePool: static-win
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty

      - name: pagerduty_success_bash
        type: Bash
        configuration:
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty

