resources:
  - name: start_all
    type: PropertyBag
    configuration:
      hello: world
  - name: bprepo
    type: GitRepo
    configuration:
      integration: johns_bbs
      path: PIP/buildplane
      branch: feature-PIPE-4793

pipelines:
  - name: pagerduty_notifications
    configuration:
      environmentVariables:
        readOnly:
          myRoutingKey: 8c22b13ccaa04da79a9952761248c337
    steps:
      - name: ps_pagerduty_success
        type: PowerShell
        configuration:
          nodePool: static-win
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty -routingkey $myRoutingKey -text "hello world from powershell"

      - name: bash_pagerduty_success
        type: Bash
        configuration:
          inputResources:
            - name: bprepo
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - pushd $res_bprepo_resourcePath
            - source execTemplates/steps/jfrog/v1.0/Bash/header.sh
            - send_notification pagerduty --routingkey $myRoutingKey --text "hello world from bash"

