resources:
  - name: tr_ext_hook_2
    type: ExternalWebhook
    configuration:
      webhookName: trriplejay_ext_hook
      method: "PUT"
      path: "/api/v2/test"
      parameters: "name=pipelinesHook"
      headers:
        content-type: application/json
        accept: test-header

  - name: tr_int_hook
    type: InternalWebhook
    configuration:
      webhookName: trriplejay_int_hook

  - name: tr_int_hook_connector
    type: InternalWebhook
    configuration:
      webhookName: trriplejay_int_hook_connector

pipelines:
  - name: tr_test_skipWebhook
    steps:
      - name: tr_skipWebhook
        type: Bash
        configuration:
          outputResources:
            - name: tr_ext_hook_2
        execution:
          onExecute:
            - set_payload tr_ext_hook_2 "{\"test\":\"payload\"}"
            - export tr_ext_hook_2_skipWebhook="true"

  - name: tr_hooks_aplenty
    steps:
      - name: tr_start_by_hook
        type: Bash
        configuration:
          environmentVariables:
            test: $step_name
          inputResources:
            - name: tr_int_hook
          outputResources:
            - name: tr_int_hook_connector
            - name: tr_ext_hook_2

        execution:
          onExecute:
            - echo "is test stepname? $test"
            - apt-get install -y tree
            - echo "Hello world"
            - echo "payload is $res_tr_int_hook_payload"
            - printenv | grep res
            - tree /jfrog
            # - set_payload tr_ext_hook  blahblah badthirdargument
            # - set_payload badresource blahblah

            - set_payload tr_ext_hook_2 "{\"test\":\"payload\"}"
            - printenv | grep payload
            - cat $tr_ext_hook_payload_file
            - export tr_ext_hook_2_skipWebhook="true"
            - set_payload tr_ext_hook_connector "{\"test\":\"payload\"}"
            # - set_payload tr_ext_hook "$step_json_path" --file
            # - printenv | grep payload
            # - cat $tr_ext_hook_payload_file
            # - set_payload tr_ext_hook /jfrog/reqExec/dist/main/libcrypto.so.1.0.0 --file
            # - printenv | grep payload

      - name: tr_hook_connection
        type: Bash
        configuration:
          inputResources:
            - name: tr_int_hook_connector
        execution:
          onExecute:
            - echo "payload is $res_tr_int_hook_connector_payload"
