resources:
  - name: tr_ext_hook
    type: ExternalWebhook
    configuration:
      webhookName: trriplejay_ext_hook
      method: "POST"
      parameters: "name=$STEP_NAME"
      headers:
        content-type: application/json

  - name: tr_int_hook
    type: InternalWebhook
    configuration:
      webhookName: trriplejay_int_hook

  - name: tr_int_hook_connector
    type: InternalWebhook
    configuration:
      webhookName: trriplejay_int_hook_connector


pipelines:
  - name: tr_hooks_aplenty
    steps:
      - name: tr_start_by_hook
        type: Bash
        configuration:
          inputResources:
            - name: tr_int_hook
          outputResources:
            - name: tr_int_hook_connector
            - name: tr_ext_hook

        execution:
          onExecute:
            - apt-get install -y tree
            - echo "Hello world"
            - echo "payload is $res_tr_int_hook_payload"
            - printenv | grep res
            - tree /jfrog
            # - set_payload tr_ext_hook  blahblah badthirdargument
            # - set_payload badresource blahblah

            - set_payload tr_ext_hook "{\"test\":\"payload\"}"
            - printenv | grep payload
            - cat $tr_ext_hook_payload_file
            # - set_payload tr_ext_hook "$step_json_path" --file
            # - printenv | grep payload
            # - cat $tr_ext_hook_payload_file
            # - set_payload tr_ext_hook /jfrog/reqExec/dist/main/libcrypto.so.1.0.0 --file
            # - printenv | grep payload

      - name: tr_hook_connection
        type: Bash
        configuration:
          inputResources:
            - name: tr_int_hook_connector
        execution:
          onExecute:
            - echo "payload is $res_tr_int_hook_connector_payload"
