resources:
  - name: webhook_test_internal
    type: webhook
    configuration:
      webhookName: trriplejay_int_hook
    version:
      payload: '{"blah": "foo"}'

  - name: webhook_test_external
    type: webhook
    configuration:
      webhookName: trriplejay_ext_hook
    version:
      payload: '{"text":"default payload. MODIFIED"}'

pipelines:
   - name: test_webhooks
     steps:
      - name: incoming_hook
        type: bash
        triggeredBy:
          resources:
            - webhook_test_internal
        execution:
          onExecute:
            - echo "whats in the resource?"
            - printenv | grep res_webhook_test_internal
            - echo "$res_webhook_test_internal_payload" | jq '.'
            - echo "ahhhhh, i see"
            - apt-get install -y tree
            - tree /reqexec
            - tree /jfrog


      - name: outgoing_hook
        type: bash
        triggeredBy:
          steps:
            - incoming_hook
        outputResources:
          - webhook_test_external
        execution:
          onExecute:
            - echo "lets write some values to the payload"
            - write_output webhook_test_external "payload={\"stepId\":\"$STEP_ID\",\"stepName\":\"$STEP_NAME\",\"message\"=\"blah blah blah\"}"
