resources:
  - name: myImage
    type: image
    configuration:
      integrationName: docker
    imageName: trriplejay/simpleserver
    initialVersion:
      imageTag: master

  - name: myOtherImage
    type: image
    configuration:
      integrationName: docker
    imageName: trriplejay/simpleserver
    initialVersion:
      imageTag: master

  - name: myRepo
    type: gitRepo
    repoPath: trriplejay/basic-node
    configuration:
      integrationName: github
    initialVersion:
      sha: master

pipelines:
  - name: scenario1
    steps:
      - name: S1_s1
        type: bash
        setup:
          affinityGroup: g1
        execution:
          onExecute:
            - echo "first step"
      - name: S1_s2
        type: bash
        setup:
          affinityGroup: g1
        requires:
          steps:
            - S1_s1
        execution:
          onExecute:
            - echo "second step"

  - name: scenario2
    steps:
      - name: S2_s1
        type: bash
        setup:
          affinityGroup: g1
        requires:
          resources:
            - myRepo
        outputResources:
          - myImage
        execution:
          onStart:
            - echo "here we go!!!"
          onExecute:
            - echo "Hello world!"
            - echo "stepId is $STEP_ID"
            - write_output myImage "imageTag=$STEP_ID"
          onSuccess:
            - echo "yay success"
          onFailure:
            - echo "boo failure"
          onComplete:
            - echo "done"
      - name: S2_s2
        type: bash
        setup:
          affinityGroup: g1
        requires:
          resources:
            - myImage
        execution:
          onStart:
            - echo "starting now"
          onExecute:
            - echo "${res_myImage_imageName}:${res_myImage_imageTag}"
