resources:
  - name: myImage
    type: image
    configuration:
      integrationName: docker
    imageName: trriplejay/simpleserver
    initialVersion:
      imageTag: master

#   - name: bad-resource-name
#     type: image
#     configuration:
#       integrationName: docker
#     imageName: trriplejay/simpleserver
#     initialVersion:
#       imageTag: master

pipelines:
  # - name: bad_pipeline_name
  #   steps:
  #     - name: blahblah
  #       type: bash
  #       execution:
  #         onExecute:
  #           - echo "hi"
  # - name: test_step_naming
  #   steps:
  #     - name: bad-step-name
  #       type: bash
  #       execution:
  #         onExecute:
  #           - echo "hi"

  - name: test_pipeline_1
    # setup:
    #   environmentVariables:
    #     readOnly:
    #       ENV1: value-pipe-1
    #       ENV2: value-pipe-2
    #   runtime:
    #     type: image
    #     image:
    #       auto: true
    #       language: java
    #       versions: v1.1
    #     custom:
    #       name: test
    #       tag: test
    #       options: test
    steps:
      - name: basic_step
        type: bash
        # configuration:
        #   affinityGroup: test_group
        setup:
        #   environmentVariables:
        #     normal:
        #       ENV1: value1
        #       ENV2: value2
        #     encrypted:
        #       SECURE_ENV1: test_value
        #       SECURE_ENV2: test_value
          runtime:
            type: image
            image:
              language: java
              versions: v1.1
            custom:
              name: drydock/u16all
              tag:  v7.1.4
        requires:
          resources:
            - myImage
          integrations:
            - docker
            - kubeconfig
        execution:
          onStart:
            - echo retry_command "here we go!!!"
          onExecute:
            - echo "Hello world!"
            - echo "step json at $STEP_JSON_PATH"
            - for item in ${!open_group_info[@]}; do echo "$item --- ${open_group_info[$item]}"; done
            - echo "testing"
            - for item in ${!open_group_info[@]}; do echo "$item --- ${open_group_info[$item]}"; done
            - echo "try again?!"
            - for item in ${!open_group_info[@]}; do echo "$item --- ${open_group_info[$item]}"; done
            - cat /pipelines/run/status/step.env
          onSuccess:
            - echo "yay success"
          onFailure:
            - echo "boo failure"
          onComplete:
            - echo "done"

      - name: fail_in_start
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
            - cat badfile
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_exec
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - cat badfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_onsucc
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
            - cat badfile
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_onfail
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - cat badfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
            - cat badfile
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_oncomp
        type: bash
        configuration:
          affinityGroup: test_group
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
            - cat badfile
          onCancel:
            - echo "Someone cancelled the job"

