resources:
  - name: neutral
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: trriplejay/basic-node

pipelines:
  - name: neutral_pipe
    steps:
      - name: neutral_step
        type: Bash
        configuration:
          inputResources:
            - name: neutral
            - name: myOtherImage_basic
        execution:
          onExecute:
            - echo "hello"



