pipelines:
  - name: tr_bad_language_test
    steps:
      - name: bad_lang
        type: bash
        setup:
          runtime:
            type: image
            image:
              auto:
                language: python
                versions:
                  - blah
        execution:
          onExecute:
            - printenv

      - name: after_bad_lang
        type: bash
        triggeredBy:
          steps:
            - bad_lang
        execution:
          onExecute:
            - echo "i always get skipped"
