pipelines:
  - name: tr_affinity_group_cancel
    steps:
      - name: first_affinity_step
        type: bash
        configuration:
          affinityGroup: cancel
        execution:
          onExecute:
            - echo "hello world"
            - sleep 30
            - echo "i'm awake, i'm awake!"

      - name: second_affinity_step
        type: bash
        configuration:
          affinityGroup: cancel
        triggeredBy:
          steps:
            - first_affinity_step
        execution:
          onExecute:
            - echo "i always get cancelled"

      - name: third_affinity_step
        type: bash
        configuration:
          affinityGroup: cancel
        triggeredBy:
          steps:
            - first_affinity_step
        execution:
          onExecute:
            - echo "i always get skipped"

  - name: tr_stuck_in_cancelling
    steps:
      - name: first_step
        type: bash
        execution:
          onExecute:
            - echo "here we go!"
            - sleep 30
            - echo "oops, i fell asleep"

      - name: second_step
        type: bash
        triggeredBy:
          steps:
            - first_step
        execution:
          onExecute:
            - echo "i always get cancelled"

      - name: third_step
        type: bash
        triggeredBy:
          steps:
            - second_step
        execution:
          onExecute:
            - echo "i always get skipped"
