pipelines:
  - name: tr_gatekeeper_chrono
    steps:
      - name: g_chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_2
        type: Bash
        configuration:
          inputSteps:
            - name: g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_3
        type: Bash
        configuration:
          inputSteps:
            - name: g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_4
        type: Bash
        configuration:
          inputSteps:
            - name: g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_5
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: g_chrono_2
            - name: g_chrono_3
            - name: g_chrono_4
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_parallel_chrono
    steps:
      - name: p_chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_2
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: p_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_3
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: p_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_4
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: p_chrono_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_5
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: p_chrono_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_serial_chrono
    steps:
      - name: chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_2
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_3
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: chrono_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_4
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: chrono_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_pipeline_chrono
    configuration:
      chronological: true
    steps:
      - name: step_1
        type: Bash
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
