pipelines:
  - name: tr_gatekeeper_chrono
    steps:
      - name: g_chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_2
        type: Bash
        triggeredBy:
          steps:
            - g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_3
        type: Bash
        triggeredBy:
          steps:
            - g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_4
        type: Bash
        triggeredBy:
          steps:
            - g_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: g_chrono_5
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - g_chrono_2
            - g_chrono_3
            - g_chrono_4
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_parallel_chrono
    steps:
      - name: p_chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_2
        type: Bash
        triggeredBy:
          steps:
            - p_chrono_1
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_3
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - p_chrono_1
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_4
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - p_chrono_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: p_chrono_5
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - p_chrono_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_serial_chrono
    steps:
      - name: chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_2
        type: Bash
        triggeredBy:
          steps:
            - chrono_1
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_3
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - chrono_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_4
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - chrono_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"

  - name: tr_pipeline_chrono
    configuration:
      chronological: true
    steps:
      - name: chrono_1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_2
        type: Bash
        triggeredBy:
          steps:
            - chrono_1
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_3
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - chrono_2
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
      - name: chrono_4
        type: Bash
        configuration:
          chronological: true
        triggeredBy:
          steps:
            - chrono_3
        execution:
          onExecute:
            - echo "here we go"
            - sleep 10
            - echo "done"
