pipelines:
  - name: tr_auto_languages
    steps:
      - name: lang_kickoff
        type: Bash
        execution:
          onExecute:
            - echo "here we go"

      - name: java_auto_11
        type: Bash
        configuration:
          inputSteps:
            - name: lang_kickoff
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: 11
        execution:
          onExecute:
            - java -version
      # - name: c_auto_8
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: lang_kickoff
      #     runtime:
      #       type: image
      #       image:
      #         auto:
      #           language: c
      #           versions:
      #             - 8.0.0
      #   execution:
      #     onExecute:
      #       - gcc --version
      #       - clang --version

      # - name: c_default
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: lang_kickoff
      #     runtime:
      #       type: image
      #       image:
      #         auto:
      #           language: c
      #   execution:
      #     onExecute:
      #       - gcc --version
      #       - clang --version
