resources:
  - name: simple_repo_master
    type: gitRepo
    repoPath: trriplejay/simpleserver
    configuration:
      integrationName: trriplejay_github
      branches:
        only: master
    version:
      sha: master

  - name: simple_image_master
    type: image
    configuration:
      integrationName: trriplejay_docker
    imageName: trriplejay/simpleserver
    version:
      imageTag: latest

  - name: simple_repo_dev
    type: gitRepo
    repoPath: trriplejay/simpleserver
    configuration:
      integrationName: trriplejay_github
      branches:
        only: dev
    version:
      sha: dev

  - name: simple_image_dev
    type: image
    configuration:
      integrationName: trriplejay_docker
    imageName: trriplejay/simpleserver
    version:
      imageTag: dev

pipelines:
  - name: tr_dev_flow
    steps:
      - name: simple_build
        type: bash
        configuration:
          affinityGroup: dev
        triggeredBy:
          resources:
            - simple_repo_dev
        execution:
          onExecute:
            - printenv | grep null
            - pushd $res_simple_repo_dev_resourcePath
            - |
              if [ "$res_simple_repo_dev_isPullRequest" == "false" ]; then
                add_run_variable dev_image_path=trriplejay/simpleserver:$STEP_ID
                export NODE_ENV=production # ignore devDependencies
                docker build --no-cache -t $dev_image_path .
              else
                npm install
                npm test
              fi
            - popd
          onFailure:
            - echo "boo"

      - name: simple_test
        type: bash
        configuration:
          affinityGroup: dev
        triggeredBy:
          steps:
            - simple_build
        requires:
          resources:
            - simple_repo_dev
        execution:
          onExecute:
            - pushd $res_simple_repo_dev_resourcePath
            - |
              if [ "$res_simple_repo_dev_isPullRequest" == "false" ]; then
                docker-compose up
                docker ps && sleep 5 && docker ps && sleep 5 && docker ps
                docker inspect $app_id
                curl localhost:8888
              fi
            - popd
          onComplete:
            - docker-compose down

      - name: simple_push
        type: bash
        configuration:
          affinityGroup: dev
        triggeredBy:
          steps:
            - simple_test
        requires:
          resources:
            - simple_repo_dev
        outputResources:
          - simple_image_dev
        execution:
          onExecute:
            - docker push $dev_image_path

      - name: simple_deploy_a
        type: bash
        triggeredBy:
          resources:
            - simple_image_dev
        execution:
          onExecute:
            - echo "deploy to test environment A"
      - name: simple_deploy_b
        type: bash
        triggeredBy:
          resources:
            - simple_image_dev
        execution:
          onExecute:
            - echo "deploy to test environment B"

  - name: tr_release_flow
    steps:
      - name: simple_master_build
        type: bash
        configuration:
          affinityGroup: master
        triggeredBy:
          resources:
            - simple_repo_dev
        outputResources:
          - simple_image_master
        execution:
          onExecute:
            - echo "build the prod version of the app"

      - name: simple_master_push
        type: bash
        configuration:
          affinityGroup: master
        triggeredBy:
          resources:
            - simple_image_master
        execution:
          onExecute:
            - echo "docker push"

      - name: simple_master_ft
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "function test"

      - name: simple_master_ut
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "unit test"
      - name: simple_master_it
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "integration test"
      - name: simple_master_deploy
        type: bash
        triggeredBy:
          steps:
            - simple_master_it
            - simple_master_ft
            - simple_master_ut
        execution:
          onExecute:
            - echo "tests passed, lets deploy"
