resources:
  - name: simple_repo_master
    type: gitRepo
    repoPath: trriplejay/simpleserver
    configuration:
      integrationName: trriplejay_github
      branches:
        only: master
    version:
      sha: master

  - name: simple_image_master
    type: image
    configuration:
      integrationName: trriplejay_docker
    imageName: trriplejay/simpleserver
    version:
      imageTag: latest

  - name: simple_repo_dev
    type: gitRepo
    repoPath: trriplejay/simpleserver
    configuration:
      integrationName: trriplejay_github
      branches:
        only: dev
    version:
      sha: dev

  - name: simple_image_dev
    type: image
    configuration:
      integrationName: trriplejay_docker
    imageName: trriplejay/simpleserver
    version:
      imageTag: dev

pipelines:
  - name: dev_build_test_push
    steps:
      - name: simple_build
        type: bash
        setup:
          affinityGroup: dev
        triggeredBy:
          resources:
            - simple_repo_dev
        outputResources:
          - simple_image_dev
        execution:
          onExecute:
            - pushd $res_simple_repo_repoPath
            - docker build -t trriplejay/simpleserver:$STEP_ID
            - write_output simple_image_dev "imageTag=$STEP_ID"

      - name: simple_test
        type: bash
        setup:
          affinityGroup: dev
        triggeredBy:
          steps:
            - simple_build
        requires:
          resources:
            - simple_image_dev
        execution:
          onExecute:
            - app_id=$(docker run -d $res_simple_image_dev_imageName:$res_simple_image_dev_imageTag)
            - curl localhost:8888
          onComplete:
            - if [ -n "$app_id" ]; then docker rm -f $app_id; fi

      - name: simple_push
        type: bash
        setup:
          affinityGroup: dev
        triggeredBy:
          steps:
            - simple_test
        requires:
          resources:
            - simple_image_dev
        execution:
          onExecute:
            - docker push $res_simple_image_dev_imageName:$res_simple_image_dev_imageTag

      - name: simple_deploy
        type: bash
        setup:
          affinityGroup: dev
        requires:
          resources:
            - simple_image_dev
        triggeredBy:
          steps:
            - simple_push
        execution:
          onExecute:
            - echo "deploy to test environment"

  - name: master_build_push_test_deploy
    steps:
      - name: simple_master_build
        type: bash
        setup:
          affinityGroup: master
        trrigeredBy:
          resources:
            - simple_repo_dev
        outputResources:
          - simple_image_master
        execution:
          onExecute:
            - echo "build the prod version of the app"

      - name: simple_master_push
        type: bash
        setup:
          affinityGroup: master
        triggeredBy:
          resources:
            - simple_image_master
        execution:
          onExecute:
            - echo "docker push"

      - name: simple_master_ft
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "function test"

      - name: simple_master_ut
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "unit test"
      - name: simple_master_it
        type: bash
        triggeredBy:
          steps:
            - simple_master_push
        execution:
          onExecute:
            - echo "integration test"
      - name: simple_master_deploy
        type: bash
        triggeredBy:
          steps:
            - simple_master_it
            - simple_master_ft
            - simple_master_ut
        execution:
          onExecute:
            - echo "tests passed, lets deploy"
