resources:
  - name: test_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/step_samples

pipelines:
  - name: git_status
    steps:
      - name: success
        type: Bash
        configuration:
          inputResources:
            - name: test_repo

        execution:
          onStart:
            - update_commit_status test_repo --status processing
            - echo "$is_success"
          onExecute:
            - update_commit_status test_repo
            - echo "$is_success"
            - cd fail
          onFailure:
            - echo "$is_success"
          onComplete:
            - echo "$is_success"
            - update_commit_status test_repo
