
pipelines:
  - name: tr_state_functions
    steps:
      - name: setup_state
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16node
                tag: master
                autoPull: false
        execution:
          onExecute:
            - add_run_variables "foo=bar" "hello=world"
            - add_pipeline_variables "pfoo=bar" "phello=world"
            - echo "here's a file! run number $run_number" >> test.txt
            - add_run_files test.txt runTest
            - echo "pipeline usage only for run $run_number and step $step_id" >> text.txt
            - add_pipeline_files test.txt pipelineTest

      - name: use_state
        type: Bash
        configuration:
          inputSteps:
            - name: setup_state
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16node
                tag: master
                autoPull: false
        execution:
          onExecute:
            - echo "Hello $hello"
            - echo "Foo $foo"
            - echo "pHello $phello"
            - echo "pFoo $pfoo"
            - restore_run_files runTest .
            - ls -latr
            - cat test.txt
            - restore_pipeline_files pipelineTest .
            - ls -latr
            - cat test.txt


