pipelines:
  - name: windows_pipe
    steps:
      - name: test_ps_1
        type: PowerShell
        configuration:
          nodePool: windows-static
        execution:
          onExecute:
            - write-output "hello world"
