resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          nodePool: u16
          inputResources:
            - name: singleRepo_simple
          runtime:
            type: image
            image:
              custom:
                name: trriplejay/helmv3
                tag: latest
                autoPull: true
        execution:
          onExecute:
            - bash --version
            - helm version
            - nvm use 10.18.0
            - node --version
            - echo "pipeline source branch is - {{gitBranch}}"

      - name: second_step_simple
        type: Bash
        configuration:
          nodePool: u16
          inputSteps:
            - name: first_step_simple
        execution:
          onExecute:
            - echo "final step in the pipeline"


