# resources:
  # - name: singleRepo_simple
  #   type: GitRepo
  #   configuration:
  #     gitProvider: johns_bbs
  #     path: ~johns/simpleserver
  #     branches:
  #       include: master

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          inputResources:
            - name: singleRepo_simple
          inputSteps:
            - name: extra_step
        execution:
          onExecute:
            - echo "pipeline source branch {{gitBranch}}"

      - name: extra_step
        type: Bash
        execution:
          onExecute:
            - echo "blah"
