resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master

  - name: singleRepo_simple_chart
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master
      files:
        include: ^simplehelm.*

  - name: singleRepo_simple_server
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master
      files:
        include:  ^server.js$

  - name: testimage
    type: Image
    configuration:
      registry: johns_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          inputResources:
            - name: singleRepo_simple
        execution:
          onExecute:
            - echo "pipeline source branch {{gitBranch}}"

  - name: three_little_steps
    steps:
      - name: extra_bad_step
        type: Bash
        configuration:
          inputResources:
            - name: singleRepo_simple_server
        execution:
          onExecute:
            - echo "ew"
      - name: parallel_step_1
        type: Bash
        configuration:
          inputResources:
            - name: testimage
            - name: singleRepo_simple_server
          inputSteps:
            - name: extra_bad_step
        execution:
          onExecute:
            - echo "hi"
      - name: parallel_step_2
        type: Bash
        configuration:
          inputResources:
            - name: testimage
            - name: singleRepo_simple
        execution:
          onExecute:
            - echo "bye"
      - name: final_step
        type: Bash
        configuration:
          inputSteps:
            - name: parallel_step_1
            - name: parallel_step_2
        execution:
          onExecute:
            - echo "hi"
