resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master

  - name: myProps
    type: PropertyBag
    configuration:
      foo: bar
      hello: world

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputResources:
            - name: singleRepo_simple
          outputResources:
            - name: myProps
          runtime:
            type: image
            image:
              custom:
                name: trriplejay/helmv3
                tag: latest
                autoPull: true
        execution:
          onExecute:
            - bash --version
            - helm version
            # - nvm use 10.18.0
            - node --version
            - echo "pipeline source branch is - {{gitBranch}}"
            - echo "hello is $hello"
            - echo "foo is $foo"
            - write_output myProps "fizz=buzz"

      - name: second_step_simple
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputResources:
            - name: myProps
        execution:
          onExecute:
            - echo "final step in the pipeline"
            - echo "fizz is $fizz"
            - echo "hello is $hello"
            - echo "foo is $foo"


