resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master

  - name: testimage
    type: Image
    configuration:
      registry: johns_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          inputResources:
            - name: singleRepo_simple
          outputResources:
            - name: testimage
        execution:
          onExecute:
            - echo "pipeline source branch {{gitBranch}}"
            - write_output testimage "imageTag={{gitBranch}}.${runNumber}"


