resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: master

  - name: myProps
    type: PropertyBag
    configuration:
      foo: bar
      hello: world

  - name: startingProps
    type: PropertyBag
    configuration:
      asdf: asdf
      not: again

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          integrations:
            - name: johns_bbs
          inputResources:
            - name: startingProps
          #   - name: singleRepo_simple
          outputResources:
            - name: myProps
        execution:
          onExecute:
            - sleep 10
            - restore_cache_files state output.txt
            - restore_pipeline_files state output.txt
            - bash --version
            # - helm version
            # - nvm use 10.18.0
            - node --version
            - echo "pipeline source branch is - {{gitBranch}}"
            - echo "hello is $hello"
            - echo "foo is $foo"
            - write_output myProps "fizz=buzz"
            - echo "hello world $run_number" >> output.txt
            - add_cache_files output.txt state
            - add_pipeline_files output.txt state
            - add_run_variables "message=heeeeeeey"
            - sleep 10

      - name: second_step_simple
        type: Bash
        configuration:
          inputResources:
            - name: myProps
        execution:
          onExecute:
            - echo "fizz is $fizz"
            - echo "hello is $hello"
            - echo "foo is $foo"
            - echo "message is $message"
      - name: third_step_simple
        type: Bash
        configuration:
          inputSteps:
            - name: second_step_simple
            - name: first_step_simple
        execution:
          onExecute:
            - echo "final step in the pipeline"


  - name: zero_day_pipeline
    steps:
      - name: zero_step_simple
        type: Bash
        configuration:
          outputResources:
            - name: startingProps
        execution:
          onExecute:
            - write_output startingProps "zero_run_number=$run_number"
