resources:
  - name: api_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: ui_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: util_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: prom_api_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: prom_ui_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: prom_util_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: app_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: blank
      version: blank
  - name: signed_app_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: blank
      version: blank
  - name: dist_rule
    type: DistributionRule
    configuration:
      sourceDistribution: johns_dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

  - name: api_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$
  - name: ui_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$
  - name: util_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$


pipelines:
  - name: johns_dist_flow
    configuration:
      nodePool: static-node-pool
    steps:
      - name: kickoff
        type: Bash
        execution:
          onExecute:
            - echo "hello world"

      - name: build_push_api
        type: Bash
        configuration:
          inputSteps:
            - name: kickoff
          integrations:
            - name: johns_art
          inputResources:
            - name: api_repo
          outputResources:
            - name: api_buildinfo
        execution:
          onExecute:
            - echo "blah"
            - pushd $res_api_repo_resourcePath
            - docker build -t pipe-master.jfrog.info:8082/simpleimages/api_image:${run_number} .
            - jfrog rt docker-push pipe-master.jfrog.info:8082/simpleimages/api_image:${run_number} simpleimages --build-name $step_name --build-number $run_number
            - jfrog rt bce $step_name $run_number
            - jfrog rt bp $step_name $run_number
            - write_output api_buildinfo "buildName=$step_name" "buildNumber=$run_number"

      - name: build_push_ui
        type: Bash
        configuration:
          inputSteps:
            - name: kickoff
          integrations:
            - name: johns_art
          inputResources:
            - name: ui_repo
          outputResources:
            - name: ui_buildinfo
        execution:
          onExecute:
            - echo "blah"
            - pushd $res_ui_repo_resourcePath
            - docker build -t pipe-master.jfrog.info:8082/simpleimages/ui_image:${run_number} .
            - jfrog rt docker-push pipe-master.jfrog.info:8082/simpleimages/ui_image:${run_number} simpleimages --build-name $step_name --build-number $run_number
            - jfrog rt bce $step_name $run_number
            - jfrog rt bp $step_name $run_number
            - write_output ui_buildinfo "buildName=$step_name" "buildNumber=$run_number"

      - name: build_push_util
        type: Bash
        configuration:
          inputSteps:
            - name: kickoff
          integrations:
            - name: johns_art
          inputResources:
            - name: util_repo
          outputResources:
            - name: util_buildinfo
        execution:
          onExecute:
            - echo "blah"
            - pushd $res_util_repo_resourcePath
            - docker build -t pipe-master.jfrog.info:8082/simpleimages/util_image:${run_number} .
            - jfrog rt docker-push pipe-master.jfrog.info:8082/simpleimages/util_image:${run_number} simpleimages --build-name $step_name --build-number $run_number
            - jfrog rt bce $step_name $run_number
            - jfrog rt bp $step_name $run_number
            - write_output util_buildinfo "buildName=$step_name" "buildNumber=$run_number"

      - name: promote_api
        type: PromoteBuild
        configuration:
          targetRepository: prod-simpleimages
          inputResources:
            - name: api_buildinfo
          outputResources:
            - name: prom_api_buildinfo

      - name: promote_ui
        type: PromoteBuild
        configuration:
          targetRepository: prod-simpleimages
          inputResources:
            - name: ui_buildinfo
          outputResources:
            - name: prom_ui_buildinfo
      - name: promote_util
        type: PromoteBuild
        configuration:
          targetRepository: prod-simpleimages
          inputResources:
            - name: util_buildinfo
          outputResources:
            - name: prom_util_buildinfo

      - name: make_bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: myApp
          releaseBundleVersion: ${run_number}
          dryRun: false
          inputResources:
            - name: prom_ui_buildinfo
            - name: prom_api_buildinfo
            - name: prom_util_buildinfo
          outputResources:
            - name: app_bundle
        execution:
          onStart:
            - export payloadPath=""
          onComplete:
            - cat $payloadPath


      # - name: sign_bundle
      #   type: SignReleaseBundle
      # - name: dist_bundle
      #   type: DistributeReleaseBundle
