resources:
  - name: api_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: ui_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: prom_api_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: prom_ui_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: ${step_name}
      buildNumber: ${run_number}
  - name: app_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: blank
      version: blank
  - name: signed_app_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: blank
      version: blank
  - name: dist_rule
    type: DistributionRule
    configuration:
      sourceDistribution: johns_dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

  - name: api_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$
  - name: ui_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$


pipelines:
  - name: johns_dist_flow
    steps:
      - name: build__push_api
        type: Bash
        configuration:
          integrations:
            - name: johns_art
          inputResources:
            - name: api_repo
          outputResources:
            - name: api_buildinfo
        execution:
          onExecute:
            - echo "blah"
            - pushd $res_api_repo_resourcePath
            - docker build -t pipe-master.jfrog.info:8082/simpleimages/ui_image:${run_number} .
            - jfrog rt docker-push pipe-master.jfrog.info:8082/simpleimages/ui_image:${run_number} simpleimages
            - jfrog rt bp $step_name $run_number
            - write_output api_buildinfo "buildName=$step_name" "buildNumber=$run_number"

      - name: build_push_ui
        type: Bash
        configuration:
          integrations:
            - name: johns_art
          inputSteps:
            - name: build_push_api
          inputResources:
            - name: ui_repo
          outputResources:
            - name: ui_buildinfo
        execution:
          onExecute:
            - echo "blah"
            - pushd $res_api_repo_resourcePath
            - docker build -t pipe-master.jfrog.info:8082/simpleimages/api_image:${run_number} .
            - jfrog rt docker-push pipe-master.jfrog.info:8082/simpleimages/api_image:${run_number} simpleimages
            - jfrog rt bp $step_name $run_number
            - write_output ui_buildinfo "buildName=$step_name" "buildNumber=$run_number"
      # - name: make_bundle
      #   type: CreateReleaseBundle
      # - name: sign_bundle
      #   type: SignReleaseBundle
      # - name: dist_bundle
      #   type: DistributeReleaseBundle
