resources:
  - name: examples_repo
    type: GitRepo
    configuration:
      path: ~johns/project-examples
      gitProvider: johns_bbs
      branches:
        include: master
  - name: g_buildinfo
    type: BuildInfo
    configuration:
      buildName: placeholder
      buildNumber: 0

pipelines:
  - name: GradleStuff
    steps:
    - name: BasicGradleSample
      type: GradleBuild
      configuration:
        sourceLocation: gradle-examples/gradle-example
        configFileLocation: .
        forceXrayScan: true
        autoPublishBuildInfo: true
        configFileName: gradle.yaml
        gradleCommand: "artifactoryPublish"
        inputResources:
          - name: examples_repo
        outputResources:
          - name: g_buildinfo
        integrations:
          - name: johns_art
          - name: johns_jira
      execution:
        onFailure:
          - send_notification johns_jira --project-id "FROG" --description "Failure occured in $pipeline_name - $step_name" --type Bug --attach-file "output.log" --summary "$step_name has failed"
