resources:
  - name: johns_publish_helmChart
    type: HelmChart
    configuration:
      sourceArtifactory: johns_artifactory
      repository: simplecharts
      chart: simpleserver
      version: 1.0.0
  - name: johns_publish_simple_git
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
  - name: johns_publish_helmChart_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_artifactory
      buildName: simplehelm
      buildNumber: 0


pipelines:
  - name: johns_test_HelmPublish
    steps:
      - name: simple_publish
        type: HelmPublish
        configuration:
          inputSteps:
            - name: testInputStep
          inputResources:
            - name: johns_publish_simple_git
          outputResources:
            - name: johns_publish_helmChart
            - name: johns_publish_helmChart_buildInfo
          autoPublishBuildInfo: true
          forceXrayScan: true
          chartPath: ./simpleserver


      - name: testInputStep
        type: Bash
        execution:
          onExecute:
            - echo "hello world"
