resources:
  - name: tr_testImage
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: tr_basic_helm
    steps:
      - name: TryIt
        type: Bash
        configuration:
          inputResources:
            - name: tr_testImage
        execution:
          onExecute:
            - echo "Hello world"
            - export HELM_FILE=helm.tar.gz
            - wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz -O /tmp/$HELM_FILE
            - tar -zxvf /tmp/$HELM_FILE
            - mv /tmp/linux-amd64/helm /usr/local/bin/helm
            - which helm
