resources:
  - name: tr_testImage
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: tr_basic_helm
    steps:
      - name: TryIt
        type: Bash
        inputResources:
          - name: tr_testImage
        execution:
          onExecute:
            - echo "Hello world"
            - which helm
