######## basic #############

resources:
  - name: johns_HelmDeploy_chart
    type: HelmChart
    configuration:
      sourceArtifactory: johns_artifactory
      repository: simplecharts
      chart: simpleserver
      version: 1.0.0

  - name: johns_HelmDeploy_git
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver
  - name: testOutImage
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: johns_test_HelmDeploy_basic_chart
    steps:
      - name: deploy_git_chart
        type: HelmDeploy
        configuration:
          environmentVariables:
            REPLICAS: 3
          integrations:
            - name: johns_kubernetes
          inputResources:
            - name: johns_publish_helmChart
          inputSteps:
            - name: testInputStep
          outputResources:
            - name: testOutImage
          releaseName: simplechart
          # valueFilePaths:
          #   - override.yaml
          flags: "--namespace dev"
          # dryRun: true
          # lint: true
          # lintFlags: "--strict"
          # test: true
          # testFlags: "--cleanup"
      - name: testInputStep
        type: Bash
        execution:
          onExecute:
            - echo "hello world"

  - name: johns_test_HelmDeploy_basic_git
    steps:
      - name: deploy_git_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: johns_kubernetes
          inputResources:
            - name: johns_HelmDeploy_git
          chartPath: ./simpleserver
          releaseName: simplegit
          flags: "--namespace dev"
          dryRun: true
          lint: true
          test: true
          testFlags: "--cleanup"



######## end basic #############
