resources:
  - name: tr_publish_helmChart
    type: HelmChart
    configuration:
      sourceArtifactory: tr_artifactory
      chart: simpleserver
      version: 1.0.0
  - name: tr_publish_simple_git
    type: GitRepo
    configuration:
      gitProvider: tr_github
      path: trriplejay/simpleserver
  - name: tr_publish_helmChart_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: tr_artifactory
      buildName: simplehelm
      buildNumber: 0


pipelines:
  - name: tr_test_HelmPublish
    steps:
      - name: simple_publish
        type: HelmPublish
        configuration:
          inputResources:
            - name: tr_publish_simple_git
          outputResources:
            - name: tr_publish_helmChart
            - name: tr_publish_helmChart_buildInfo
          autoPublishBuildInfo: true
          forceXrayScan: true
          chartPath: ./simpleserver
