resources:
  - name: johns_testImage
    type: Image
    configuration:
      registry: johns_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: johns_basic_helm
    steps:
      - name: TryIt
        type: Bash
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: johns_testImage
        execution:
          onExecute:
            - echo "Hello world"
            - which helm
            - helm init --client-only
            - helm repo add helm-remote $int_art_url/helm-remote --username $int_art_user --password $int_art_apikey
            - helm repo update
            - helm repo list
            - helm search helm-remote/
            - helm search -l helm-remote/consul
