resources:
  - name: johns_HelmAdvanced_chart
    type: HelmChart
    configuration:
      sourceArtifactory: johns_art
      repository: simplecharts
      chart: simpleserver
      version: 1.0.0

  - name: johns_HelmAdvanced_git
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simpleserver

  - name: johns_HelmAdvanced_simpleImage
    type: Image
    configuration:
      registry: johns_art
      sourceRepository: simpleimages
      imageName: trriplejay/simpleserver
      imageTag: latest

  - name: johns_HelmAdvanced_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: HelmAdvanced
      buildNumber: 0

pipelines:
  - name: helm_full_flow
    steps:
      - name: build
        type: DockerBuild
        configuration:
          integrations:
            - name: johns_art
          inputResources:
            - name: johns_HelmAdvanced_git
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: trriplejay/simpleserver
          dockerImageTag: $run_number
      - name: push
        type: DockerPush
        configuration:
          integrations:
            - name: johns_art
          targetRepository: johns/simpleserver
          autoPublishBuildInfo: true
          forceXrayScan: true
          inputSteps:
            - name: build
          outputResources:
            - name: johns_HelmAdvanced_buildInfo
            - name: johns_HelmAdvanced_simpleImage

      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          inputResources:
            - name: johns_HelmAdvanced_git
          outputResources:
            - name: johns_HelmAdvanced_chart
          chartPath: ./simpleserver

      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: johns_kubernetes
          inputResources:
            - name: johns_HelmAdvanced_chart
            - name: johns_HelmAdvanced_simpleImage
          releaseName: simplechart
          dryRun: true
          lint: true
          test: true
