######## basic #############

resources:
  - name: tr_HelmDeploy_chart
    type: HelmChart
    configuration:
      sourceArtifactory: tr_artifactory
      repository: simplecharts
      chart: simpleserver
      version: 1.0.0

  - name: tr_HelmDeploy_git
    type: GitRepo
    configuration:
      gitProvider: tr_github
      path: trriplejay/simpleserver

pipelines:
  - name: tr_test_HelmDeploy_basic_chart
    steps:
      - name: deploy_git_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: tr_kubernetes
          inputResources:
            - name: tr_publish_helmChart
          releaseName: simplechart
          flags: "--namespace dev"
          dryRun: true
          lint: true
          lintFlags: "--strict"
          test: true
          testFlags: "--cleanup"

  - name: tr_test_HelmDeploy_basic_git
    steps:
      - name: deploy_git_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: tr_kubernetes
          inputResources:
            - name: tr_HelmDeploy_git
          chartPath: ./simpleserver
          releaseName: simplegit
          dryRun: true
          lint: true
          test: true

######## end basic #############
