resources:
  - name: tr_testImage
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

pipelines:
  - name: tr_basic_helm
    steps:
      - name: TryIt
        type: Bash
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: tr_testImage
        execution:
          onExecute:
            - echo "Hello world"
            - pushd /tmp
            - wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
            - tar -zxvf helm-v2.14.3-linux-amd64.tar.gz
            - mv linux-amd64/helm /usr/local/bin/helm
            - popd
            - which helm
            - helm init --client-only
            - helm repo add helm-remote $int_art_url/helm-remote --username $int_art_user --password $int_art_apikey
            - helm repo update
            - helm repo list
            - helm search helm-remote/
            - helm search -l helm-remote/consul
