######## basic #############

resources:
  # - name: johns_HelmDeploy_chart
  #   type: HelmChart
  #   configuration:
  #     sourceArtifactory: johns_art
  #     repository: simplecharts
  #     chart: simpleserver
  #     version: 1.0.0

  - name: johns_HelmDeploy_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simplehelm

pipelines:
  # - name: johns_test_HelmDeploy_basic_chart
  #   steps:
  #     - name: deploy_git_chart
  #       type: HelmDeploy
  #       syntaxVersion: 2.0
  #       configuration:
  #         environmentVariables:
  #           REPLICAS: 3
  #         integrations:
  #           - name: johns_kubernetes
  #         inputResources:
  #           - name: johns_publish_helmChart
  #         releaseName: simplechart
  #         # valueFilePaths:
  #         #   - override.yaml
  #         flags: "--namespace dev"
  #         # dryRun: true
  #         # lint: true
  #         # lintFlags: "--strict"
  #         # test: true
  #         # testFlags: "--cleanup"

  - name: johns_test_HelmDeploy_basic_git
    steps:
      - name: deploy_git_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: johns_kubernetes
          inputResources:
            - name: johns_HelmDeploy_repo
          chartPath: ./simplehelm
          releaseName: simplegit
          flags: "--namespace dev"
          dryRun: true
          lint: true
          test: true
          testFlags: "--cleanup"
        execution:
          onStart:
            - cat -n "$steplet_script_path"



######## end basic #############
