resources:
  - name: johns_HelmAdvanced_chart
    type: HelmChart
    configuration:
      sourceArtifactory: johns_art
      repository: simplecharts
      chart: simplehelm
      version: 1.0.0

  - name: johns_HelmAdvanced_source
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/simplehelm

  - name: johns_HelmAdvanced_simpleImg
    type: Image
    configuration:
      registry: johns_art
      sourceRepository: simpleimages
      imageName: pipe-master.jfrog.info:8082/simpleimages/simpleserver
      imageTag: latest

  - name: johns_HelmAdvanced_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: HelmAdvanced
      buildNumber: 0

pipelines:
  - name: helm_full_flow
    steps:
      - name: build
        type: DockerBuild
        configuration:
          integrations:
            - name: johns_art
          inputResources:
            - name: johns_HelmAdvanced_source
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipe-master.jfrog.info:8082/simpleimages/simpleserver
          dockerImageTag: ${run_number}
      - name: push
        type: DockerPush
        configuration:
          integrations:
            - name: johns_art
          targetRepository: simpleimages
          autoPublishBuildInfo: true
          forceXrayScan: false
          inputSteps:
            - name: build
          outputResources:
            - name: johns_HelmAdvanced_buildInfo
            - name: johns_HelmAdvanced_simpleImg

      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          inputResources:
            - name: johns_HelmAdvanced_source
          outputResources:
            - name: johns_HelmAdvanced_chart
          chartPath: ./simplehelm

      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: johns_kubernetes
          inputResources:
            - name: johns_HelmAdvanced_chart
            - name: johns_HelmAdvanced_simpleImg
          releaseName: simplechart
          dryRun: true
          lint: true
          test: true
