resources:
  - name: java_repo
    type: GitRepo
    configuration:
      path: ~johns/java-backend
      gitProvider: johns_bbs
      branches:
        include: master
pipelines:
  - name: MavenStuff
    steps:
    - name: BuildSample
      type: MvnBuild
      configuration:
        sourceLocation: .
        configFileLocation: .
        configFileName: mvn-art-config
        mvnCommand: "clean install -ntp"
        inputResources:
          - name: java_repo
        integrations:
          - name: johns_art
