resources:
  - name: examples_repo
    type: GitRepo
    configuration:
      path: ~johns/project-examples
      gitProvider: johns_bbs
      branches:
        include: master
pipelines:
  - name: MavenStuff
    steps:
    # - name: BuildSample
    #   type: MvnBuild
    #   configuration:
    #     sourceLocation: artifactory-maven-plugin-example
    #     configFileLocation: .
    #     configFileName: config
    #     mvnCommand: "install -P release"
    #     inputResources:
    #       - name: examples_repo
    #     integrations:
    #       - name: johns_art


  ### with jira for log attachment
    - name: BuildSample
      type: MvnBuild
      configuration:
        sourceLocation: artifactory-maven-plugin-example
        configFileLocation: .
        configFileName: config
        mvnCommand: "install -P release --log-file ${step_tmp_dir}/log.txt"
        inputResources:
          - name: examples_repo
        integrations:
          - name: johns_art
          - mame: johns_jira
      execution:
        onFailure:
          - cat $step_tmp_dir/log.txt
          - send_notification johns_jira --project-id "FROG" --description "Failure occured in $pipeline_name - $step_name" --type Bug --attach-file "$step_tmp_dir/log.txt" --summary "$step_name has failed"
