resources:
  - name: examples_repo
    type: GitRepo
    configuration:
      path: ~johns/project-examples
      gitProvider: johns_bbs
      branches:
        include: master
pipelines:
  - name: MavenStuff
    steps:
    - name: BuildSample
      type: MvnBuild
      configuration:
        sourceLocation: artifactory-maven-plugin-example
        configFileLocation: .jfrog/projects/
        configFileName: maven.yaml
        mvnCommand: "install -P release"
        inputResources:
          - name: examples_repo
        integrations:
          - name: johns_art
      execution:
        onStart:
          - update-ca-certificates -f
