resources:
  - name: johns_image_test
    type: Image
    configuration:
      registry: johns_docker
      imageName: trriplejay/simpleserver
      imageTag: master

  - name: johns_buildinfo_test
    type: BuildInfo
    configuration:
      sourceArtifactory: trriplejay_art
      buildNumber: 5
      buildName: helloWorld

  - name: johns_buildinfo_test_2
    type: BuildInfo
    configuration:
      sourceArtifactory: trriplejay_art
      buildNumber: 5
      buildName: helloWorld

  - name: johns_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: trriplejay_art
      buildNumber: 5
      buildName: helloWorld

  - name: johns_npm_repo
    type: GitRepo
    configuration:
      path: trriplejay/simpleserver
      gitProvider: johns_bbs

pipelines:
  - name: johns_pbi_validation
    steps:
    ## used for setup
      - name: johns_bash
        type: Bash
        execution:
          onExecute:
            - echo "hello"

      - name: johns_mvnBuild
        type: MvnBuild
        configuration:
          integrations:
            - name: trriplejay_art
          inputResources:
            - name: johns_npm_repo
          sourceLocation: $res_johns_npm_repo_resourcePath
          mvnCommand: mvn --version
          configFileLocation: $res_johns_npm_repo_resourcePath/config
          configFileName: c.config

      - name: johns_mvnBuild_auto
        type: MvnBuild
        configuration:
          autoPublishBuildInfo: true
          integrations:
            - name: trriplejay_art
          inputResources:
            - name: johns_npm_repo
          sourceLocation: $res_johns_npm_repo_resourcePath
          mvnCommand: mvn --version
          configFileLocation: $res_johns_npm_repo_resourcePath/config
          configFileName: c.config

      - name: johns_nb_test
        type: NpmBuild
        configuration:
          affinityGroup: npm
          inputResources:
            - name: johns_npm_repo
          sourceLocation: $res_johns_npm_repo_resourcePath
          repositoryName: simpleserver
          integrations:
            - name: trriplejay_art

    ## main test steps
      - name: johns_pbi_twoThings
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: johns_mvnBuild
            - name: johns_bash
          integrations:
            - name: trriplejay_art
          outputResources:
            - name: johns_buildinfo_test
            - name: johns_buildinfo_test_2

      - name: johns_pbi_badTypes
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: johns_nb_test
          integrations:
            - name: trriplejay_art
          outputResources:
            - name: johns_image_test

      - name: johns_pbi_notification
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: johns_mvnBuild
          integrations:
            - name: trriplejay_slack
          outputResources:
            - name: johns_buildinfo_test

      - name: johns_pbi_autoPub
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: johns_mvnBuild_auto
          outputResources:
            - name: johns_buildinfo_test


############### pipeline split

  - name: johns_pbi_execution
    steps:
      - name: johns_nb
        type: NpmBuild
        configuration:
          affinityGroup: npm
          inputResources:
            - name: johns_npm_repo
          sourceLocation: $res_johns_npm_repo_resourcePath
          repositoryName: simpleserver
          integrations:
            - name: trriplejay_art

      - name: johns_np
        type: NpmPublish
        configuration:
          affinityGroup: npm
          inputSteps:
            - name: johns_nb
          integrations:
            - name: trriplejay_art
          repositoryName: simpleserver

      - name: johns_pbi_execute
        type: PublishBuildInfo
        configuration:
          affinityGroup: npm
          inputSteps:
            - name: johns_np
          outputResources:
            - name: johns_buildinfo

