resources:
  - name: tr_buildinfo_test
    type: BuildInfo
    configuration:
      sourceArtifactory: trriplejay_art
      buildNumber: 5
      buildName: helloWorld

  - name: tr_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: trriplejay_art
      buildNumber: 5
      buildName: helloWorld

  - name: tr_npm_repo
    type: GitRepo
    configuration:
      path: trriplejay/simpleserver
      gitProvider: trriplejay_github

pipelines:
  - name: tr_pbi_validation
    steps:
    ## used for setup
      - name: tr_bash
        type: Bash
        execution:
          onExecute:
            - echo "hello"

      - name: tr_mvnBuild
        type: MvnBuild
        configuration:
          integrations:
            - name: trriplejay_art
          inputResources:
            - name: tr_npm_repo
          sourceLocation: $res_tr_npm_repo_resourcePath
          mvnCommand: mvn --version
          configFileLocation: $res_tr_npm_repo_resourcePath/config
          configFileName: c.config


    ## main test steps
      - name: tr_pbi
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: tr_mvnBuild
          integrations:
            - name: trriplejay_art
          outputResources:
            - name: tr_buildinfo_test


  - name: tr_pbi_execution
    steps:
      - name: tr_nb
        type: NpmBuild
        configuration:
          affinityGroup: npm
          inputResources:
            - name: tr_npm_repo
          sourceLocation: $res_tr_npm_repo_resourcePath
          repositoryName: simpleserver
          integrations:
            - name: trriplejay_art

      - name: tr_np
        type: NpmPublish
        configuration:
          affinityGroup: npm
          inputSteps:
            - name: tr_nb
          integrations:
            - name: trriplejay_art
          repositoryName: simpleserver

      - name: tr_pbi_execute
        type: PublishBuildInfo
        configuration:
          affinityGroup: npm
          inputSteps:
            - name: tr_np
          outputResources:
            - name: tr_buildinfo

