resources:
  - name: johns_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: iot_art
      buildName: test_bundle
      buildNumber: 0

  - name: johns_release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: johns_test_bundle
      version: 1.0.0
      isSigned: false

  - name: johns_signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: johns_dist
      name: johns_signed_bundle
      version: 1.0.0
      isSigned: true

  - name: johns_dist_rule
    type: DistributionRule
    configuration:
      sourceDistribution: johns_dist
      serviceName: "rt-edge-sea-1"
      siteName: "SeattleEdge"
      cityName: "*"
      countryCodes:
        - "*"

pipelines:
  - name: johns_release_pipe
    steps:
      - name: push_package
        type: Bash
        configuration:
          outputResources:
            - name: johns_buildinfo
          integrations:
            - name: iot_art
        execution:
          onExecute:
            - echo "hello world. Package arrived from run ${run_number}." > package_${run_number}.txt
            - jfrog rt u --build-name ${pipeline_name} --build-number ${run_number} package.txt johns_stuff/package.txt
            - jfrog rt bce ${pipeline_name} ${run_number}
            - jfrog rt bp ${pipeline_name} ${run_number}
          onSuccess:
            - write_output johns_buildinfo "buildName=${pipeline_name}" "buildNumber=${run_number}"

      - name: create_bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: johns_test_bundle
          releaseBundleVersion: ${run_number}
          sign: true
          dryRun: false
          storeAtSourceArtifactory: "true"
          description: "my bundle ready for release"
          inputResources:
            - name: johns_buildinfo
          outputResources:
            - name: johns_release_bundle

      - name: distribute_bundle
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: johns_release_bundle
            - name: johns_dist_rule
