
pipelines:
  - name: tr_custom_image
    steps:
      - name: basic_node
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: trriplejay/ubuntu
                tag: "16.04"
                autoPull: true
                # sourceRepository: pipelines-docker
                registry: johns_docker
        execution:
          onExecute:
            - echo "Hello world"
            - printenv
            - cat $step_json_path

  - name: tr_custom_pipe_image
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: trriplejay/ubuntu
            tag: "16.04"
            autoPull: true
            # sourceRepository: pipelines-docker
            registry: johns_docker
    steps:
      - name: basic_stuff
        type: Bash
        execution:
          onExecute:
            - echo "hello world"
            - printenv
            - cat $step_json_path
