
pipelines:
  - name: tr_custom_image
    steps:
      - name: basic_node
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                version:
                  - "8.16"
              # custom:
              #   name: pipelines-docker.jfrog.io/jfrog/pipelines-u16node
              #   tag: master
              #   autoPull: false
        execution:
          onExecute:
            - echo "Hello world"
