resources:
  - name: johns_ExtHook
    type: ExternalWebhook
    configuration:
      webhookName: johns_ext_hook
      path: /url
      headers:
        content-type: application/x-www-form-urlencoded

pipelines:
  - name: johns_simple_ext_hook
    steps:
      - name: johns_send_hook
        type: Bash
        configuration:
          outputResources:
            - name: johns_ExtHook
        execution:
          onExecute:
            - echo "hello world"
            - jsonPayload="{\"runNumber\":\"$run_number\", \"stepName\":\"$step_name\"}"
            - formUrlEncodedPayload="foo=bar&runNumber=$run_number&stepName=$step_name"
            - set_payload johns_ExtHook "$formUrlEncodedPayload"
