resources:
  - name: johns_ExtHook
    type: ExternalWebhook
    configuration:
      webhookName: johns_ext_hook
      path: /my/path

pipelines:
  - name: johns_simple_ext_hook
    steps:
      - name: johns_send_hook
        type: Bash
        configuration:
          outputResources:
            - name: johns_ExtHook
        execution:
          onExecute:
            - echo "hello world"
            - easy_payload="{\"hello\":\"world\"}"
            - dynamic_payload="{\"runNumber\":\"$run_number\", \"stepName\":\"$step_name\"}"
            - set_payload johns_ExtHook $dynamic_payload
